- name: Install Pip.
  apt: name=python-pip state=installed
  sudo: yes

- name: Install Docker Python library.
  pip: name=docker-py state=present
  sudo: yes

- name: Mariadb container
  docker:
    docker_api_version: "1.16"
    name: wordpressdb
    image: mariadb
    pull: always
    state: reloaded
    restart_policy: always
    env:
      MYSQL_ROOT_PASSWORD: password
    use_tls: "no"
    detach: false

- name: Wordpress container
  docker:
    docker_api_version: "1.16"
    name: wordpress
    image: wordpress:4
    pull: always
    state: reloaded
    restart_policy: always
    links:
      - "wordpressdb:mysql"
    env:
      WORDPRESS_DB_PASSWORD: password
    # Environment for postgresl
    # https://github.com/docker-library/wordpress/blob/ba89e6a1834c7142b9d8ac7a0353dcd0205a4312/apache/docker-entrypoint.sh 
    #env:
    #  MYSQL_PORT_3306_TCP: 5432
    #  WORDPRESS_DB_HOST: 192.168.10.10:5432
    #  WORDPRESS_DB_USER: "wordpress"
    #  WORDPRESS_DB_PASSWORD: "wordpress"
    #  WORDPRESS_DB_NAME: "wordpress"
    ports:
      - 8080:80
    use_tls: "no"
    detach: false

# detach=False not working as expected
# https://github.com/ansible/ansible-modules-core/issues/706
- name: wait containers to finish
  shell: >
    docker wait wordpressdb wordpress


#- name: MySQL container
#  command: "docker run
#    --name wordpressdb
#    -e MYSQL_ROOT_PASSWORD=password
#    -e MYSQL_DATABASE=wordpress
#    -d mysql:5.7"
#
#- name: Wordpress container
#  command: "docker run
#    -e WORDPRESS_DB_PASSWORD=password
#    --name wordpress
#    --link wordpressdb:mysql
#    -p 8080:80
#    -d wordpress"

# Try to link with postgres
# docker run --name some-wordpress -e WORDPRESS_DB_HOST=192.168.10.10:5432 -e WORDPRESS_DB_USER=wordpress -e WORDPRESS_DB_PASSWORD=wordpress -e WORDPRESS_DB_NAME=wordpress -p 8080:80 -d wordpress

# How to use the official docker wordpress image
# docker run --name wordpressdb -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=wordpress -d mysql:5.7
# docker run -e WORDPRESS_DB_PASSWORD=password -d --name wordpress --link wordpressdb:mysql -p 8080:80  wordpress


